/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saglik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servis ayakta mı */
        get: operations["saglik_saglik_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/konum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Koordinatın tarımsal kimlik kartı (parsel hariç)
         * @description Yer adı, ülke, yükselti ve 30 yıllık iklim normali.
         *
         *     Toprak ve parsel BİLEREK dahil edilmez, ayrı uç noktalardadır (bkz modül
         *     başlığı, madde 1). Hiçbir katman akışı durdurmaz; gelmeyen katmanlar
         *     `eksik` listesinde isimleriyle bildirilir, sessizce boş geçilmez.
         */
        get: operations["konum_konum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toprak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Toprak özellikleri (SoilGrids, ISRIC)
         * @description Ayrı uç noktadır çünkü SoilGrids gecikmesi ölçümde 1-40 saniye arası.
         *
         *     `durum` alanını okumadan boş toprağı yorumlamayın: "ok" değilse bu
         *     "burada toprak verisi yok" DEĞİL, "sunucuya ulaşılamadı" demektir.
         *     Sonuç bir kez alındığında diske yazılır, aynı 1 km hücresi bir daha
         *     beklemez.
         */
        get: operations["toprak_toprak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parseller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yakındaki tarım parselleri (OpenStreetMap)
         * @description Ayrı uç noktadır çünkü önbellekte yoksa 25 saniyeye kadar sürebilir.
         *
         *     `durum` alanını okumadan boş listeyi yorumlamayın: "ok" değilse liste boş
         *     olsa bile bu "parsel yok" demek DEĞİLDİR, "sunucuya ulaşılamadı" demektir.
         */
        get: operations["parseller_parseller_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oneri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bu koordinatta ne yetişir (FAO EcoCrop)
         * @description Sıralama 30 yıllık iklim normali + SoilGrids toprağı ile hesaplanır.
         *
         *     Puan bir UYGUNLUK puanıdır, karlılık değildir: pazar fiyatı, sözleşmeli
         *     tarım ve sulama altyapısı EcoCrop'ta yoktur. "Burada ne yetişir" sorusunu
         *     yanıtlar, "burada en çok ne kazandırır" sorusunu değil.
         */
        get: operations["oneri_oneri_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oneri/gruplar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Her ürün grubundan en iyi N ürün
         * @description Sadece tepe listeyi göstermek çiftçiyi tek gruba boğuyor (hepsi meyve
         *     çıkabiliyor). Gerçek seçenek sunmak için gruplar ayrı ayrı döner.
         */
        get: operations["oneri_gruplar_oneri_gruplar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rastgele": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dünyanın rastgele bir tarım bölgesinden konum
         * @description Tamamen rastgele koordinat ~%70 okyanus çıkardığı için seçim dünyanın
         *     başlıca tarım havzalarıyla sınırlıdır.
         *
         *     Toprak ve parsel aranmaz: 12 deneme x (25 s parsel + 60 s toprak) bütçesi en
         *     kötü durumda 17 dakika ederdi. Nokta döndükten sonra /toprak ve /parseller
         *     ayrıca çağrılır.
         */
        get: operations["rastgele_rastgele_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kisayollar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Önbelleği hazır olan hızlı erişim noktaları
         * @description Ücretsiz barındırmada disk kalıcı olmadığı için bu noktaların önbelleği
         *     depoya gömülüdür ve kutudan çıkar çıkmaz hazır gelir.
         *
         *     BU LİSTE UYGULAMAYI HIZLANDIRMAZ. Önbellek anahtarı koordinatı yaklaşık
         *     1 km'lik hücreye yuvarlar; dünyanın kara yüzeyi ~149 milyon km2. Birkaç
         *     düzine nokta rastgele bir tıklamayı yakalamaz. Sadece BURADAKİ noktalar
         *     anında gelir. Bu yüzden arayüzde "popüler" ya da "önerilen" diye değil,
         *     hızlı erişim kısayolu olarak sunulur.
         *
         *     Ağ isteği yapmaz: yer adı yalnızca önbellekte varsa doldurulur.
         */
        get: operations["kisayollar_kisayollar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/urunler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bilgi tabanındaki tüm ürünler
         * @description Arayüzdeki grup filtresi ve ürün arama kutusu bunu kullanır.
         *
         *     `don_dinlenme_kaynak` alanı kasıtlı olarak dışarı verilir: kış dayanıklılığı
         *     değerlerinin bir kısmı EcoCrop'ta boş olduğu için elle tamamlandı ve hangi
         *     değerin nereden geldiği gizlenmemelidir.
         */
        get: operations["urunler_urunler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teshis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yaprak fotoğrafından hastalık teşhisi (ONNX)
         * @description Yaprak fotoğrafı yükle, hastalık etiketi + tedavi kaydı al.
         *
         *     Boyut sınırı 6 MB, MIME tipi image/* olmalıdır. Yanıt sözleşmesi TeshisYanit.
         */
        post: operations["teshis_teshis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_teshis_teshis_post */
        Body_teshis_teshis_post: {
            /**
             * Dosya
             * @description Yaprak fotoğrafı (JPG/PNG).
             */
            dosya: string;
        };
        /**
         * ClimateData
         * @description Open-Meteo'dan gelen iklim ozeti.
         */
        ClimateData: {
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Rainfall */
            rainfall?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IklimOzet */
        IklimOzet: {
            /** Yillik Yagis Mm */
            yillik_yagis_mm?: number | null;
            /** En Sicak Ay C */
            en_sicak_ay_c?: number | null;
            /** En Soguk Ay C */
            en_soguk_ay_c?: number | null;
            /** Mutlak Min C */
            mutlak_min_c?: number | null;
            /**
             * Yil Sayisi
             * @default 0
             */
            yil_sayisi: number;
            /** Ay Sicaklik */
            ay_sicaklik?: (number | null)[];
            /** Ay Yagis */
            ay_yagis?: (number | null)[];
        };
        /** KisayolYanit */
        KisayolYanit: {
            /**
             * Kisayol Ad
             * @description Listeyi hazırlarken düştüğüm not. VERİ DEĞİLDİR, sadece düğmenin üstünde yazan etikettir.
             */
            kisayol_ad: string;
            /**
             * Yer Adi
             * @description OpenStreetMap'ten gelen gerçek yer adı. Önbellekte yoksa null döner; uydurulmaz. Arayüz null ise kisayol_ad yazar.
             */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Hazir Katmanlar
             * @description Önbellekte gerçekten bulunan katmanlar: "yer", "iklim", "toprak", "parsel". Eksik olan katman düğmeye basınca canlı sorgulanır, yani o katman yavaş açılır.
             */
            hazir_katmanlar: string[];
            /**
             * Isitildi
             * @description Dördü de hazır mı. False ise düğme YİNE ÇALIŞIR, sadece eksik katmanlar beklenir. Bu alan yer adının varlığına değil dört katmanın hepsine bakar.
             */
            isitildi: boolean;
        };
        /** KonumYanit */
        KonumYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Yer Adi */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            /**
             * Karada
             * @default true
             */
            karada: boolean;
            /** Yukselti M */
            yukselti_m?: number | null;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Toprak Kaynak Mesafe Km
             * @description Toprak verisi tam noktadan gelmediyse kaç km uzaktan alındığı
             */
            toprak_kaynak_mesafe_km?: number | null;
            /**
             * Toprak Durum
             * @description Bu uç noktada normalde "sorgulanmadi" olur: toprak yavaş katmandır ve /toprak uç noktasından ayrıca istenir.
             * @default sorgulanmadi
             */
            toprak_durum: string;
            /** @description 30 yıllık normal. Öneri motorunun kullandığı sayının aynısıdır; nem alanı bu kaynakta yoktur. */
            iklim?: components["schemas"]["ClimateData"] | null;
            /** Eksik */
            eksik?: string[];
            /** Sure S */
            sure_s: number;
        };
        /** OneriKumesi */
        OneriKumesi: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Yer Adi */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Toprak Var
             * @description False ise puanlama SADECE iklime dayanır, pH ve doku faktörleri hesaba girmemiştir.
             */
            toprak_var: boolean;
            /**
             * Toprak Durum
             * @description Toprak yoksa nedeni: "ok" gerçekten veri yok, başka bir değer SoilGrids'e ulaşılamadı.
             */
            toprak_durum: string;
            iklim: components["schemas"]["IklimOzet"];
            /**
             * Toplam Uygun
             * @description Elenmeden kalan ürün sayısı
             */
            toplam_uygun: number;
            /**
             * Su Anki Ay
             * @description Sunucunun bulunduğu takvim ayı. Arayüz 'şimdi ekilebilir' ile 'mevsiminde ekilebilir' ayrımını buna göre yapar. Sunucudan gelir çünkü ayrım bir veri sonucudur, kullanıcı cihazının saatine bırakılmamalıdır.
             */
            su_anki_ay: string;
            /** Oneriler */
            oneriler: components["schemas"]["OneriYanit"][];
            /** Sure S */
            sure_s: number;
        };
        /** OneriYanit */
        OneriYanit: {
            /** Urun */
            urun: string;
            /** Ad */
            ad: string;
            /**
             * Bilimsel Ad
             * @default
             */
            bilimsel_ad: string;
            /**
             * Grup
             * @default
             */
            grup: string;
            /** Skor */
            skor: number;
            /** Uygunluk */
            uygunluk: string;
            /** Cok Yillik */
            cok_yillik: boolean;
            /** Ekim Ayi */
            ekim_ayi?: string | null;
            /** Hasat Ayi */
            hasat_ayi?: string | null;
            /**
             * Ekim Aylari
             * @description İklim olarak ekilebilir bulunan TÜM aylar: en iyi ekim ayının puanının %95'inden aşağı düşmeyen aylar. Çok yıllıklarda boştur, çünkü ağaç ekilmez fidan dikilir ve dikim zamanı EcoCrop'ta yoktur. Bu bir EKİM TAKVİMİ DEĞİLDİR: yalnızca sıcaklık uygunluğudur, vernalizasyon ve gün uzunluğu hesaba girmez.
             */
            ekim_aylari?: string[];
            /**
             * Merkezlik
             * @description Ölçülen değerlerin ürünün optimum aralığının neresinde durduğu: 1.0 tam ortası, 0.0 kenarı. PUANA DAHİL DEĞİLDİR; EcoCrop optimum aralığın içini eşit derecede uygun sayar. Aynı puanı alan ürünleri ayırt etmek içindir.
             * @default 0
             */
            merkezlik: number;
            /**
             * Su Acigi Mm
             * @default 0
             */
            su_acigi_mm: number;
            /**
             * Uygunluk Gaez
             * @description FAO GAEZ v4 Suitability Index (0-100), bu koordinatta bu ürünün ne kadar iyi yetiştiğinin bölgesel ölçümü. Skor buradan 0.7 ağırlıkla hesaba girer; EcoCrop trapezoidinin sıkıştırdığı 90-100 aralığını bölgesel gerçeklikle açar. None ise GAEZ'de bu ürüne eşleme yok veya konum GAEZ yüksek çözünürlük bölgesi (20-48 E, 33-44 N) dışında.
             */
            uygunluk_gaez?: number | null;
            /** Faktorler */
            faktorler?: {
                [key: string]: unknown;
            }[];
            /** Uyarilar */
            uyarilar?: string[];
            /**
             * Sezon
             * @default
             */
            sezon: string;
            /**
             * Notlar
             * @default
             */
            notlar: string;
        };
        /** ParselYanit */
        ParselYanit: {
            /** Osm Id */
            osm_id: number;
            /** Tur */
            tur: string;
            /** Tur Tr */
            tur_tr: string;
            /** Alan M2 */
            alan_m2?: number | null;
            /** Alan Dekar */
            alan_dekar?: number | null;
            /** Merkez Lat */
            merkez_lat?: number | null;
            /** Merkez Lon */
            merkez_lon?: number | null;
            /** Ad */
            ad?: string | null;
            /** Sinir */
            sinir?: [
                number,
                number
            ][];
        };
        /** ParsellerYanit */
        ParsellerYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Durum
             * @description "ok" ise liste kesindir; boşsa gerçekten parsel yok. Başka bir değerse sunucuya ulaşılamadı, parsel olup olmadığı BİLİNMİYOR.
             */
            durum: string;
            /**
             * Kesin
             * @description durum == "ok" mi. Arayüz boş listeyi "parsel yok" diye yazmadan önce buna bakmalı.
             */
            kesin: boolean;
            /** Adet */
            adet: number;
            /** Parseller */
            parseller: components["schemas"]["ParselYanit"][];
            /** Sure S */
            sure_s: number;
        };
        /**
         * SoilData
         * @description SoilGrids'ten gelen toprak ozellikleri (koordinattan).
         */
        SoilData: {
            /** Ph */
            ph?: number | null;
            /** Nitrogen */
            nitrogen?: number | null;
            /** Clay */
            clay?: number | null;
            /** Sand */
            sand?: number | null;
            /** Silt */
            silt?: number | null;
            /** Organic Carbon */
            organic_carbon?: number | null;
        };
        /** TedaviKaydi */
        TedaviKaydi: {
            /** Ad */
            ad: string;
            /**
             * Konak
             * @default []
             */
            konak: string[];
            /**
             * Belirti
             * @default
             */
            belirti: string;
            /**
             * Dogal
             * @default
             */
            dogal: string;
            /**
             * Kimyasal
             * @default
             */
            kimyasal: string;
            /**
             * Korunma
             * @default
             */
            korunma: string;
        };
        /**
         * TeshisYanit
         * @description Yaprak fotografindan hastalik teshis sonucu.
         *
         *     seviye anlami:
         *       - kesin: yuksek guven + margin (dogrudan tedavi one cikar)
         *       - olasi: orta guven veya cekismeli iki sinif (kullaniciya alternatif goster)
         *       - belirsiz: guven cok dusuk (yeni foto iste)
         *       - tanimsiz: model 'diger' dedi (hedef urunlerden biri degil)
         */
        TeshisYanit: {
            /**
             * Etiket
             * @description Model etiketi (ASCII, snake_case).
             */
            etiket: string;
            /**
             * Etiket Tr
             * @description Turkce ad, kullanicida gosterilir.
             */
            etiket_tr: string;
            /** Guven */
            guven: number;
            /**
             * Margin
             * @description Top1 - Top2 guven farki.
             */
            margin: number;
            /**
             * Seviye
             * @description kesin | olasi | belirsiz | tanimsiz
             */
            seviye: string;
            /** Belirsiz */
            belirsiz: boolean;
            /**
             * Sebep
             * @description hedef_disi | cekismeli | orta_guven | guven_dusuk
             */
            sebep?: string | null;
            /**
             * Urun
             * @description Tahmin edilen urun grubu (ornek 'domates').
             */
            urun?: string | null;
            /** Urun Tr */
            urun_tr: string | null;
            /** Urun Guven */
            urun_guven: number;
            /** Topk */
            topk: components["schemas"]["TopKMadde"][];
            /** @description treatments.yaml kaydi. Saglikli/tanimsiz icin null. */
            tedavi?: components["schemas"]["TedaviKaydi"] | null;
            /**
             * Uyari
             * @description Seviyeye gore kullaniciya mesaj.
             */
            uyari?: string | null;
        };
        /** TopKMadde */
        TopKMadde: {
            /**
             * Etiket
             * @description Model etiketi, ornek 'domates_erken_yaniklik'.
             */
            etiket: string;
            /** Guven */
            guven: number;
        };
        /** ToprakYanit */
        ToprakYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Durum
             * @description "ok" ise sonuç kesindir. Başka bir değerse SoilGrids yanıt vermedi, toprak "yok" değil BİLİNMİYOR demektir.
             */
            durum: string;
            /** Kesin */
            kesin: boolean;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Kaynak Mesafe Km
             * @description 0 ise değer tam bu noktanın. Büyükse SoilGrids bu noktada boştu ve değer bu kadar uzaktaki komşu noktadan alındı.
             */
            kaynak_mesafe_km?: number | null;
            /** Doku Sinifi */
            doku_sinifi?: string | null;
            /** Sure S */
            sure_s: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saglik_saglik_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    konum_konum_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonumYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toprak_toprak_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToprakYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parseller_parseller_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Arama yarıçapı. Geniş yarıçap Overpass'ta 504 aldığı için üst sınır 10 km. */
                yaricap_m?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsellerYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oneri_oneri_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Kaç ürün dönsün */
                adet?: number;
                /** @description Tek bir ürün grubuyla sınırla (tahıl, sebze, meyve ...) */
                grup?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneriKumesi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oneri_gruplar_oneri_gruplar_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                grup_basina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rastgele_rastgele_get: {
        parameters: {
            query?: {
                /** @description Aynı noktayı tekrar üretmek için */
                tohum?: number | null;
                deneme?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonumYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kisayollar_kisayollar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KisayolYanit"][];
                };
            };
        };
    };
    urunler_urunler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    teshis_teshis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_teshis_teshis_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeshisYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
