/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saglik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servis ayakta mı */
        get: operations["saglik_saglik_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/konum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Koordinatın tarımsal kimlik kartı (parsel hariç)
         * @description Yer adı, ülke, yükselti ve 30 yıllık iklim normali.
         *
         *     Toprak ve parsel BİLEREK dahil edilmez, ayrı uç noktalardadır (bkz modül
         *     başlığı, madde 1). Hiçbir katman akışı durdurmaz; gelmeyen katmanlar
         *     `eksik` listesinde isimleriyle bildirilir, sessizce boş geçilmez.
         */
        get: operations["konum_konum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toprak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Toprak özellikleri (SoilGrids, ISRIC)
         * @description Ayrı uç noktadır çünkü SoilGrids gecikmesi ölçümde 1-40 saniye arası.
         *
         *     `durum` alanını okumadan boş toprağı yorumlamayın: "ok" değilse bu
         *     "burada toprak verisi yok" DEĞİL, "sunucuya ulaşılamadı" demektir.
         *     Sonuç bir kez alındığında diske yazılır, aynı 1 km hücresi bir daha
         *     beklemez.
         */
        get: operations["toprak_toprak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/besin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Toprak besin karnesi (0-30 cm sürüm katmanı)
         * @description Ölçülen toprak değerlerinden ne çıkarılabileceğini, ne çıkarılamayacağını
         *     birlikte verir.
         *
         *     İlk sorgu ~5 saniye sürer: üç derinlik ayrı ayrı çekilir. Sonuç diske
         *     yazılır, aynı hücre bir daha beklemez.
         */
        get: operations["besin_karnesi_uc_besin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parseller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yakındaki tarım parselleri (OpenStreetMap)
         * @description Ayrı uç noktadır çünkü önbellekte yoksa 25 saniyeye kadar sürebilir.
         *
         *     `durum` alanını okumadan boş listeyi yorumlamayın: "ok" değilse liste boş
         *     olsa bile bu "parsel yok" demek DEĞİLDİR, "sunucuya ulaşılamadı" demektir.
         */
        get: operations["parseller_parseller_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oneri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bu koordinatta ne yetişir (FAO EcoCrop)
         * @description Sıralama 30 yıllık iklim normali + SoilGrids toprağı ile hesaplanır.
         *
         *     Puan bir UYGUNLUK puanıdır, karlılık değildir: pazar fiyatı, sözleşmeli
         *     tarım ve sulama altyapısı EcoCrop'ta yoktur. "Burada ne yetişir" sorusunu
         *     yanıtlar, "burada en çok ne kazandırır" sorusunu değil.
         */
        get: operations["oneri_oneri_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oneri/gruplar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Her ürün grubundan en iyi N ürün
         * @description Sadece tepe listeyi göstermek çiftçiyi tek gruba boğuyor (hepsi meyve
         *     çıkabiliyor). Gerçek seçenek sunmak için gruplar ayrı ayrı döner.
         */
        get: operations["oneri_gruplar_oneri_gruplar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rastgele": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dünyanın rastgele bir tarım bölgesinden konum
         * @description Tamamen rastgele koordinat ~%70 okyanus çıkardığı için seçim dünyanın
         *     başlıca tarım havzalarıyla sınırlıdır.
         *
         *     Toprak ve parsel aranmaz: 12 deneme x (25 s parsel + 60 s toprak) bütçesi en
         *     kötü durumda 17 dakika ederdi. Nokta döndükten sonra /toprak ve /parseller
         *     ayrıca çağrılır.
         */
        get: operations["rastgele_rastgele_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kisayollar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Önbelleği hazır olan hızlı erişim noktaları
         * @description Ücretsiz barındırmada disk kalıcı olmadığı için bu noktaların önbelleği
         *     depoya gömülüdür ve kutudan çıkar çıkmaz hazır gelir.
         *
         *     BU LİSTE UYGULAMAYI HIZLANDIRMAZ. Önbellek anahtarı koordinatı yaklaşık
         *     1 km'lik hücreye yuvarlar; dünyanın kara yüzeyi ~149 milyon km2. Birkaç
         *     düzine nokta rastgele bir tıklamayı yakalamaz. Sadece BURADAKİ noktalar
         *     anında gelir. Bu yüzden arayüzde "popüler" ya da "önerilen" diye değil,
         *     hızlı erişim kısayolu olarak sunulur.
         *
         *     Ağ isteği yapmaz: yer adı yalnızca önbellekte varsa doldurulur.
         */
        get: operations["kisayollar_kisayollar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/urunler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bilgi tabanındaki tüm ürünler
         * @description Arayüzdeki grup filtresi ve ürün arama kutusu bunu kullanır.
         *
         *     `don_dinlenme_kaynak` alanı kasıtlı olarak dışarı verilir: kış dayanıklılığı
         *     değerlerinin bir kısmı EcoCrop'ta boş olduğu için elle tamamlandı ve hangi
         *     değerin nereden geldiği gizlenmemelidir.
         */
        get: operations["urunler_urunler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teshis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yaprak fotoğrafından hastalık teşhisi (ONNX)
         * @description Yaprak fotoğrafı yükle, hastalık etiketi + tedavi kaydı al.
         *
         *     Boyut sınırı 6 MB, MIME tipi image/* olmalıdır. Yanıt sözleşmesi TeshisYanit.
         *
         *     Günlük gönderilirse teşhisin kendisi DEĞİŞMEZ; yalnızca `tekrar` alanı
         *     dolar. Modelin çıktısını geçmiş kayda göre kaydırmak, aynı fotoğrafın
         *     iki farklı çiftçide iki farklı sonuç vermesi demek olurdu.
         */
        post: operations["teshis_teshis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kapsam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Her tarla hesabının kapsadığı ürünler
         * @description Hangi hesabın hangi ürünü cevaplayabildiği.
         *
         *     Arayüz bunu bir kez çeker ve ürün listesinde kapsam dışı olanları
         *     gizlemek yerine sebebiyle birlikte işaretler.
         */
        get: operations["kapsam_listesi_kapsam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sulama": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * FAO-56 günlük sulama planı
         * @description Önümüzdeki 7 günün ET0 ve yağış tahmininden net sulama ihtiyacı.
         *
         *     Net sulama = ETc - etkili yağış. Sonuç bir üst sınır değil ihtiyaçtır:
         *     toprak nemi, sulama yönteminin verimi ve tuzluluk yıkama payı bu hesapta
         *     yoktur.
         */
        get: operations["sulama_sulama_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gunluk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Son sulamadan bu yana biriken su açığı
         * @description Sezon günlüğündeki son sulama tarihi + ölçülen hava verisi.
         *
         *     Sulama gününün kendisi hesaba katılmaz (toprak o gün zaten ıslaktır),
         *     ertesi günden başlanır. Yağışın %80'i etkili sayılır (FAO-56).
         */
        get: operations["gunluk_su_acigi_gunluk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iklim-riski": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 16 günlük tahminden ürüne özel risk
         * @description Don, soğuk, sıcak, aşırı yağış ve kuraklık riskleri.
         *
         *     Eşikler ürünün EcoCrop sıcaklık trapezinden gelir, genel bir hava uyarısı
         *     değildir: aynı 5 °C gece domates için riskli, zeytin için değildir.
         */
        get: operations["iklim_risk_iklim_riski_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zararli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Derece-gün ile zararlı nesil/evre tahmini
         * @description 1 Mart'tan bugüne biriken derece-gün ile zararlının hangi evrede olduğu.
         *
         *     Mücadele zamanlaması için izleme penceresi verir, ilaçlama reçetesi değildir.
         *     Ürünün tabloda kaydı yoksa liste boş döner; bu hata değildir.
         */
        get: operations["zararli_zararli_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/karbon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IPCC 2019 Tier 1 sezonluk sera gazı envanteri
         * @description Parselin bir sezonluk sera gazı salımı ve azaltım karşılıkları.
         *
         *     Beş kalem: gübreden doğrudan/dolaylı N2O, gübre üretimi, dizel, sulama
         *     pompası elektriği. Sulama kalemi uydurulmaz, tarlanın kendi FAO-56
         *     planından gelir; bu yüzden ürünün Kc katsayısı zorunludur.
         *
         *     Toprak karbon stoku, üre hidrolizi ve kireçleme kapsam dışıdır ve yanıtta
         *     'kapsam_disi' olarak listelenir; sessizce sıfır sayılmaz.
         */
        get: operations["karbon_ayak_izi_karbon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serbest metin sorusunu doğru uzmana yönlendirir
         * @description Çiftçinin kendi cümlesini hangi hesabın cevaplayacağını bulur.
         *
         *     Anahtar kelime eşleşmesi Türkçe karakterden bağımsızdır ('böcek' ve
         *     'bocek' aynı yere gider). Hiçbir eşleşme olmazsa genel danışmana düşer;
         *     'anlamadım' denmez.
         *
         *     `son_sulama` verilirse sulama cevabına, o günden bu yana biriken net su
         *     açığı eklenir. Plan DEĞİŞMEZ; eklenen şey, planın çiftçinin kendi
         *     geçmişiyle birlikte okunmasını sağlayan ikinci bir cümledir.
         */
        get: operations["sor_sor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parseller/tkgm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repodaki TKGM parsel sorgu sonuçları
         * @description Kayıtlı gerçek parseller: merkez koordinat ve resmi alan.
         *
         *     Canlı MEGSIS servisine gitmez. TKGM'nin parsel sorgu API'si kurumsal
         *     erişim ister (istek HTML giriş sayfasına yönleniyor), bu yüzden sorgu
         *     sonuçları dosya olarak tutuluyor. Kullanıcı haritada elle nokta aramak
         *     yerine kendi parselini listeden seçer; alan da elle girilmez, tapudaki
         *     değer gelir.
         */
        get: operations["tkgm_parselleri_parseller_tkgm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BesinBolumu */
        BesinBolumu: {
            /** Anahtar */
            anahtar: string;
            /** Baslik */
            baslik: string;
            /** Deger */
            deger: number;
            /**
             * Birim
             * @default
             */
            birim: string;
            /** Sinif */
            sinif?: string | null;
            /** Aciklama */
            aciklama: string;
        };
        /** BesinEksik */
        BesinEksik: {
            /** Anahtar */
            anahtar: string;
            /** Sebep */
            sebep: string;
        };
        /** BesinUrunu */
        BesinUrunu: {
            /** Ad */
            ad?: string | null;
            /**
             * Verimlilik
             * @description EcoCrop FER alanı: low | moderate | high.
             */
            verimlilik?: string | null;
            /** Ph Araligi */
            ph_araligi?: {
                [key: string]: unknown;
            } | null;
            /** Notlar */
            notlar?: string[];
        };
        /**
         * BesinYanit
         * @description Toprak besin karnesi.
         *
         *     GÜBRE DOZU İÇERMEZ ve bu bir eksiklik değil, bilerek verilmiş bir karardır:
         *     doz hesabı ürünün kaldırdığı azot tablosunu ve toprağın mineralizasyon
         *     hızını ister; ikisi de ölçülemiyor. Uydurulmuş bir doz, tarlaya gerçek
         *     gübre attırırdı. Bunun yerine ölçülenden kesin çıkanlar verilir ve
         *     ölçülemeyenler için hangi laboratuvar testinin isteneceği yazılır.
         */
        BesinYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Durum
             * @description "ok" ise sonuç kesindir.
             */
            durum: string;
            /** Kesin */
            kesin: boolean;
            /**
             * Derinlik Cm
             * @description Ölçümün derinliği. Laboratuvar raporlarıyla aynı sürüm katmanı olsun diye üç SoilGrids katmanı kalınlıkla ağırlıklandırılır; 0-5 cm tek başına organik maddeyi ölçülen üç Türk tarım noktasında 1.79-1.80 kat fazla gösteriyordu.
             */
            derinlik_cm: number;
            /** Olculen */
            olculen: {
                [key: string]: components["schemas"]["OlculenDeger"];
            };
            /** Bolumler */
            bolumler: components["schemas"]["BesinBolumu"][];
            /**
             * Eksik
             * @description Ölçümü gelmediği için HESAPLANMAYAN bölümler ve sebebi.
             */
            eksik: components["schemas"]["BesinEksik"][];
            /**
             * Kilitli
             * @description Toprakta bulunsa bile bu pH'ta bitkinin alamayacağı elementler.
             */
            kilitli: components["schemas"]["KilitliElement"][];
            /**
             * Laboratuvar
             * @description Uydu verisinden ölçülemeyen elementler için istenecek test.
             */
            laboratuvar: components["schemas"]["LabTesti"][];
            urun?: components["schemas"]["BesinUrunu"] | null;
            /** Sure S */
            sure_s: number;
        };
        /** Body_teshis_teshis_post */
        Body_teshis_teshis_post: {
            /**
             * Dosya
             * @description Yaprak fotoğrafı (JPG/PNG).
             */
            dosya: string;
            /**
             * Gunluk
             * @description Sezon günlüğü kayıtları, JSON dizisi: [{"tarih":"2026-07-05","tur":"teshis","etiket":"..."}]. Verilirse aynı hastalığın tekrarı yanıtta bildirilir.
             */
            gunluk?: string | null;
        };
        /**
         * ClimateData
         * @description Open-Meteo'dan gelen iklim ozeti.
         */
        ClimateData: {
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Rainfall */
            rainfall?: number | null;
        };
        /**
         * GunlukYanit
         * @description Son sulamadan bu yana biriken net su açığı.
         *
         *     /sulama'dan FARKI, ve bu fark özelliğin varlık sebebidir: /sulama
         *     ÖNÜMÜZDEKİ 7 günün tahminine bakar ve "günde kaç mm ver" der. Burası
         *     GEÇMİŞE bakar ve "en son suladığın günden bu yana ne kadar borç
         *     birikti" der. İkincisi tarlanın kendi geçmişi olmadan hesaplanamaz;
         *     hafızanın cevabı değiştirdiği tek yer budur.
         *
         *     Açık, toprakta o kadar su EKSİK demek değildir: toprağın tuttuğu nem
         *     bu hesapta yok (ölçülmüyor). Bitkinin o günlerde tükettiği su ile o
         *     günlerde düşen yağışın farkıdır.
         */
        GunlukYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Urun */
            urun: string;
            /** Urun Tr */
            urun_tr: string;
            /** Asama */
            asama: string;
            /** Asama Tr */
            asama_tr: string;
            /** Son Sulama */
            son_sulama: string;
            /** Gecen Gun */
            gecen_gun: number;
            /** Kc */
            kc: number;
            /**
             * Etc Mm
             * @description Geçen günlerin toplam bitki su tüketimi.
             */
            etc_mm: number;
            /**
             * Yagis Mm
             * @description Aynı günlerin ölçülen ham yağışı.
             */
            yagis_mm: number;
            /**
             * Etkili Yagis Mm
             * @description Yağışın bitkiye ulaşan kısmı (%80).
             */
            etkili_yagis_mm: number;
            /** Acik Mm */
            acik_mm: number;
            /** Litre Dekar */
            litre_dekar: number;
            /** Yorum */
            yorum: string;
            /**
             * Kayit Tarihi
             * @description Doluysa gösterilen sayılar canlı veriden değil, bu tarihte çekilip depoya gömülen anlık kayıttan geliyor demektir.
             */
            kayit_tarihi?: string | null;
            /** Uyari */
            uyari: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IklimOzet */
        IklimOzet: {
            /** Yillik Yagis Mm */
            yillik_yagis_mm?: number | null;
            /** En Sicak Ay C */
            en_sicak_ay_c?: number | null;
            /** En Soguk Ay C */
            en_soguk_ay_c?: number | null;
            /** Mutlak Min C */
            mutlak_min_c?: number | null;
            /**
             * Yil Sayisi
             * @default 0
             */
            yil_sayisi: number;
            /** Ay Sicaklik */
            ay_sicaklik?: (number | null)[];
            /** Ay Yagis */
            ay_yagis?: (number | null)[];
        };
        /** IklimRiskYanit */
        IklimRiskYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Gun
             * @description Değerlendirilen tahmin günü sayısı.
             */
            gun: number;
            /** Urunler */
            urunler: components["schemas"]["UrunRiski"][];
            /**
             * Kayit Tarihi
             * @description Doluysa gösterilen sayılar canlı veriden değil, bu tarihte çekilip depoya gömülen anlık kayıttan geliyor demektir.
             */
            kayit_tarihi?: string | null;
            /** Uyari */
            uyari: string;
        };
        /** KapsamUrunu */
        KapsamUrunu: {
            /** Anahtar */
            anahtar: string;
            /**
             * Ad
             * @description Arayüzde görünen Türkçe ad.
             */
            ad: string;
        };
        /**
         * KapsamYanit
         * @description Bir yetenegin cevaplayabildigi urunler. Arayuz listeyi buna gore isaretler.
         */
        KapsamYanit: {
            /** Yetenek */
            yetenek: string;
            /** Urunler */
            urunler: components["schemas"]["KapsamUrunu"][];
            /**
             * Gerekce
             * @description Kapsam dışı üründe gösterilecek sebep.
             */
            gerekce: string;
        };
        /** KarbonAzaltim */
        KarbonAzaltim: {
            /** Baslik */
            baslik: string;
            /** Aciklama */
            aciklama: string;
            /**
             * Kazanc Kg Co2E
             * @description Bu adımın bu tarladaki karşılığı.
             */
            kazanc_kg_co2e: number;
        };
        /** KarbonKalemi */
        KarbonKalemi: {
            /** Ad */
            ad: string;
            /** Kg Co2E */
            kg_co2e: number;
            /**
             * Kaynak
             * @description Kullanılan emisyon faktörü ve kaynağı.
             */
            kaynak: string;
        };
        /** KarbonYanit */
        KarbonYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Urun */
            urun: string;
            /** Urun Tr */
            urun_tr: string;
            /** Dekar */
            dekar: number;
            /** Sezon Gun */
            sezon_gun: number;
            /**
             * Gosterge
             * @description Gübre/yakıt girilmediyse true.
             */
            gosterge: boolean;
            /** Azot Kg Da */
            azot_kg_da: number;
            /** Dizel L Da */
            dizel_l_da: number;
            /** Sulama Yontemi */
            sulama_yontemi: string;
            /** Su Kaynagi */
            su_kaynagi: string;
            /** Et0 Mm Gun */
            et0_mm_gun: number;
            /** Net Mm Gun */
            net_mm_gun: number;
            /** Sulama M3 */
            sulama_m3: number;
            /** Sulama Kwh */
            sulama_kwh: number;
            /** Su Senaryosu */
            su_senaryosu: string;
            /** Kalemler */
            kalemler: components["schemas"]["KarbonKalemi"][];
            /** Toplam Kg Co2E */
            toplam_kg_co2e: number;
            /** Dekar Basina Kg Co2E */
            dekar_basina_kg_co2e: number;
            /** Azaltim */
            azaltim: components["schemas"]["KarbonAzaltim"][];
            /** Kapsam Disi */
            kapsam_disi: string[];
            /**
             * Kayit Tarihi
             * @description Doluysa gösterilen sayılar canlı veriden değil, bu tarihte çekilip depoya gömülen anlık kayıttan geliyor demektir.
             */
            kayit_tarihi?: string | null;
            /** Aciklama */
            aciklama: string;
        };
        /** KilitliElement */
        KilitliElement: {
            /** Element */
            element: string;
            /** Sebep */
            sebep: string;
        };
        /**
         * Kirpma
         * @description Modelin gercekte gordugu kare, ORIJINAL fotografin pikselinde.
         *
         *     Model kisa kenari 224'e olcekleyip merkezden kare kesiyor; kullanici ise
         *     tam fotografi goruyor. Isi haritasi tam fotografin uzerine cizilseydi
         *     kenarlardaki kayma yuzunden isi yanlis yaprak parcasina duserdi.
         */
        Kirpma: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Boyut
             * @description Kare kenari (piksel).
             */
            boyut: number;
            /**
             * Genislik
             * @description Yuklenen fotografin genisligi.
             */
            genislik: number;
            /**
             * Yukseklik
             * @description Yuklenen fotografin yuksekligi.
             */
            yukseklik: number;
        };
        /** KisayolYanit */
        KisayolYanit: {
            /**
             * Kisayol Ad
             * @description Listeyi hazırlarken düştüğüm not. VERİ DEĞİLDİR, sadece düğmenin üstünde yazan etikettir.
             */
            kisayol_ad: string;
            /**
             * Yer Adi
             * @description OpenStreetMap'ten gelen gerçek yer adı. Önbellekte yoksa null döner; uydurulmaz. Arayüz null ise kisayol_ad yazar.
             */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Hazir Katmanlar
             * @description Önbellekte gerçekten bulunan katmanlar: "yer", "iklim", "toprak", "parsel". Eksik olan katman düğmeye basınca canlı sorgulanır, yani o katman yavaş açılır.
             */
            hazir_katmanlar: string[];
            /**
             * Isitildi
             * @description Dördü de hazır mı. False ise düğme YİNE ÇALIŞIR, sadece eksik katmanlar beklenir. Bu alan yer adının varlığına değil dört katmanın hepsine bakar.
             */
            isitildi: boolean;
        };
        /** KonumYanit */
        KonumYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Yer Adi */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            /**
             * Karada
             * @default true
             */
            karada: boolean;
            /** Yukselti M */
            yukselti_m?: number | null;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Toprak Kaynak Mesafe Km
             * @description Toprak verisi tam noktadan gelmediyse kaç km uzaktan alındığı
             */
            toprak_kaynak_mesafe_km?: number | null;
            /**
             * Toprak Durum
             * @description Bu uç noktada normalde "sorgulanmadi" olur: toprak yavaş katmandır ve /toprak uç noktasından ayrıca istenir.
             * @default sorgulanmadi
             */
            toprak_durum: string;
            /** @description 30 yıllık normal. Öneri motorunun kullandığı sayının aynısıdır; nem alanı bu kaynakta yoktur. */
            iklim?: components["schemas"]["ClimateData"] | null;
            /** Eksik */
            eksik?: string[];
            /** Sure S */
            sure_s: number;
        };
        /** LabTesti */
        LabTesti: {
            /** Element */
            element: string;
            /** Test */
            test: string;
            /** Gerekce */
            gerekce: string;
        };
        /** OlculenDeger */
        OlculenDeger: {
            /** Ad */
            ad: string;
            /** Deger */
            deger: number;
            /** Birim */
            birim: string;
        };
        /** OneriKumesi */
        OneriKumesi: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Yer Adi */
            yer_adi?: string | null;
            /** Ulke */
            ulke?: string | null;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Toprak Var
             * @description False ise puanlama SADECE iklime dayanır, pH ve doku faktörleri hesaba girmemiştir.
             */
            toprak_var: boolean;
            /**
             * Toprak Durum
             * @description Toprak yoksa nedeni: "ok" gerçekten veri yok, başka bir değer SoilGrids'e ulaşılamadı.
             */
            toprak_durum: string;
            iklim: components["schemas"]["IklimOzet"];
            /**
             * Toplam Uygun
             * @description Elenmeden kalan ürün sayısı
             */
            toplam_uygun: number;
            /**
             * Su Anki Ay
             * @description Sunucunun bulunduğu takvim ayı. Arayüz 'şimdi ekilebilir' ile 'mevsiminde ekilebilir' ayrımını buna göre yapar. Sunucudan gelir çünkü ayrım bir veri sonucudur, kullanıcı cihazının saatine bırakılmamalıdır.
             */
            su_anki_ay: string;
            /** Oneriler */
            oneriler: components["schemas"]["OneriYanit"][];
            /** Sure S */
            sure_s: number;
        };
        /** OneriYanit */
        OneriYanit: {
            /** Urun */
            urun: string;
            /** Ad */
            ad: string;
            /**
             * Bilimsel Ad
             * @default
             */
            bilimsel_ad: string;
            /**
             * Grup
             * @default
             */
            grup: string;
            /** Skor */
            skor: number;
            /** Uygunluk */
            uygunluk: string;
            /** Cok Yillik */
            cok_yillik: boolean;
            /** Ekim Ayi */
            ekim_ayi?: string | null;
            /** Hasat Ayi */
            hasat_ayi?: string | null;
            /**
             * Ekim Aylari
             * @description İklim olarak ekilebilir bulunan TÜM aylar: en iyi ekim ayının puanının %95'inden aşağı düşmeyen aylar. Çok yıllıklarda boştur, çünkü ağaç ekilmez fidan dikilir ve dikim zamanı EcoCrop'ta yoktur. Bu bir EKİM TAKVİMİ DEĞİLDİR: yalnızca sıcaklık uygunluğudur, vernalizasyon ve gün uzunluğu hesaba girmez.
             */
            ekim_aylari?: string[];
            /**
             * Merkezlik
             * @description Ölçülen değerlerin ürünün optimum aralığının neresinde durduğu: 1.0 tam ortası, 0.0 kenarı. PUANA DAHİL DEĞİLDİR; EcoCrop optimum aralığın içini eşit derecede uygun sayar. Aynı puanı alan ürünleri ayırt etmek içindir.
             * @default 0
             */
            merkezlik: number;
            /**
             * Su Acigi Mm
             * @default 0
             */
            su_acigi_mm: number;
            /**
             * Uygunluk Gaez
             * @description FAO GAEZ v4 Suitability Index (0-100), bu koordinatta bu ürünün ne kadar iyi yetiştiğinin bölgesel ölçümü. Skor buradan 0.7 ağırlıkla hesaba girer; EcoCrop trapezoidinin sıkıştırdığı 90-100 aralığını bölgesel gerçeklikle açar. None ise GAEZ'de bu ürüne eşleme yok veya konum GAEZ yüksek çözünürlük bölgesi (20-48 E, 33-44 N) dışında.
             */
            uygunluk_gaez?: number | null;
            /** Faktorler */
            faktorler?: {
                [key: string]: unknown;
            }[];
            /** Uyarilar */
            uyarilar?: string[];
            /**
             * Sezon
             * @default
             */
            sezon: string;
            /**
             * Notlar
             * @default
             */
            notlar: string;
        };
        /** ParselYanit */
        ParselYanit: {
            /** Osm Id */
            osm_id: number;
            /** Tur */
            tur: string;
            /** Tur Tr */
            tur_tr: string;
            /** Alan M2 */
            alan_m2?: number | null;
            /** Alan Dekar */
            alan_dekar?: number | null;
            /** Merkez Lat */
            merkez_lat?: number | null;
            /** Merkez Lon */
            merkez_lon?: number | null;
            /** Ad */
            ad?: string | null;
            /** Sinir */
            sinir?: [
                number,
                number
            ][];
        };
        /** ParsellerYanit */
        ParsellerYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Durum
             * @description "ok" ise liste kesindir; boşsa gerçekten parsel yok. Başka bir değerse sunucuya ulaşılamadı, parsel olup olmadığı BİLİNMİYOR.
             */
            durum: string;
            /**
             * Kesin
             * @description durum == "ok" mi. Arayüz boş listeyi "parsel yok" diye yazmadan önce buna bakmalı.
             */
            kesin: boolean;
            /** Adet */
            adet: number;
            /** Parseller */
            parseller: components["schemas"]["ParselYanit"][];
            /** Sure S */
            sure_s: number;
        };
        /** RiskMaddesi */
        RiskMaddesi: {
            /**
             * Tur
             * @description don | soguk | sicak | yagis | kuraklik
             */
            tur: string;
            /**
             * Tur Tr
             * @description Arayüzde gösterilen okunur ad.
             */
            tur_tr: string;
            /**
             * Seviye
             * @description yuksek | orta | dusuk
             */
            seviye: string;
            /** Aciklama */
            aciklama: string;
        };
        /**
         * SoilData
         * @description SoilGrids'ten gelen toprak ozellikleri (koordinattan).
         *
         *     bulk_density ve cec besin karnesi icin eklendi (bkz. knowledge/besin.py):
         *     yigin yogunlugu olmadan "kac kg azot var" sorusu HESAPLANAMAZ, sadece
         *     tahmin edilebilir; KDK ise topragin besini tutma kapasitesinin dogrudan
         *     olcumudur, kil yuzdesinden cikarilan bir vekil degil.
         *
         *     Eski onbellek kayitlarinda bu iki alan YOK; None kalirlar ve besin karnesi
         *     o hesabi yapmadigini soyler. Sessizce varsayilan deger konmaz.
         */
        SoilData: {
            /** Ph */
            ph?: number | null;
            /** Nitrogen */
            nitrogen?: number | null;
            /** Clay */
            clay?: number | null;
            /** Sand */
            sand?: number | null;
            /** Silt */
            silt?: number | null;
            /** Organic Carbon */
            organic_carbon?: number | null;
            /** Bulk Density */
            bulk_density?: number | null;
            /** Cec */
            cec?: number | null;
        };
        /** SoruYanit */
        SoruYanit: {
            /** Soru */
            soru: string;
            /**
             * Niyet
             * @description Router'ın seçtiği uzman.
             */
            niyet: string;
            /** Niyet Tr */
            niyet_tr: string;
            /**
             * Sekme
             * @description Cevabın görüldüğü arayüz sekmesi.
             */
            sekme: string;
            /** Cevap */
            cevap: string;
            /**
             * Veri
             * @description Uzmanın ham çıktısı.
             */
            veri?: {
                [key: string]: unknown;
            };
            /**
             * Yonlendirme
             * @description Cevap yerine sekmeye yönlendirildi mi.
             */
            yonlendirme: boolean;
        };
        /** SulamaPlani */
        SulamaPlani: {
            /** Urun */
            urun: string;
            /** Urun Tr */
            urun_tr: string;
            /** Stage */
            stage: string;
            /**
             * Kc
             * @description FAO-56 bitki katsayısı.
             */
            kc: number;
            /** Et0 Mm Gun */
            et0_mm_gun: number;
            /**
             * Etc Mm Gun
             * @description Bitki su tüketimi ET0 x Kc.
             */
            etc_mm_gun: number;
            /**
             * Net Mm Gun
             * @description Etkili yağış düşülmüş net sulama.
             */
            net_mm_gun: number;
            /**
             * Litre Gun
             * @description Parsel alanı verildiyse L/gün.
             */
            litre_gun?: number | null;
        };
        /** SulamaYanit */
        SulamaYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Et0 Mm Gun */
            et0_mm_gun: number;
            /** Yagis Mm Donem */
            yagis_mm_donem: number;
            /** Gun */
            gun: number;
            /** Asama */
            asama: string;
            /** Asama Tr */
            asama_tr: string;
            /** Planlar */
            planlar: components["schemas"]["SulamaPlani"][];
            /**
             * Kayit Tarihi
             * @description Doluysa gösterilen sayılar canlı veriden değil, bu tarihte çekilip depoya gömülen anlık kayıttan geliyor demektir.
             */
            kayit_tarihi?: string | null;
            /** Uyari */
            uyari: string;
        };
        /** TedaviKaydi */
        TedaviKaydi: {
            /** Ad */
            ad: string;
            /**
             * Konak
             * @default []
             */
            konak: string[];
            /**
             * Belirti
             * @default
             */
            belirti: string;
            /**
             * Dogal
             * @default
             */
            dogal: string;
            /**
             * Kimyasal
             * @default
             */
            kimyasal: string;
            /**
             * Korunma
             * @default
             */
            korunma: string;
        };
        /**
         * TekrarKaydi
         * @description Ayni hastaligin gunlukte daha once yazilmis olmasi.
         *
         *     HUKUM ICERMEZ. "Ilac ise yaramadi" demiyoruz: ayni hastaligin tekrar
         *     gorulmesinin ilacin etkisizligi, yanlis doz, yeniden bulasma veya komsu
         *     tarladan tasinma gibi ayirt edemedigimiz sebepleri olabilir. Yan yana
         *     konan iki olgu, gunluge bakan ciftcinin zaten gorecegi seydir.
         */
        TekrarKaydi: {
            /** Onceki Tarih */
            onceki_tarih: string;
            /** Gecen Gun */
            gecen_gun: number;
            /**
             * Ilac Sayisi
             * @description İki teşhis arasında kayıtlı ilaçlama sayısı.
             */
            ilac_sayisi: number;
            /** Ilac Son */
            ilac_son?: string | null;
            /** Cumle */
            cumle: string;
        };
        /**
         * TeshisYanit
         * @description Yaprak fotografindan hastalik teshis sonucu.
         *
         *     seviye anlami:
         *       - kesin: yuksek guven + margin (dogrudan tedavi one cikar)
         *       - olasi: orta guven veya cekismeli iki sinif (kullaniciya alternatif goster)
         *       - belirsiz: guven cok dusuk (yeni foto iste)
         *       - tanimsiz: model 'diger' dedi (hedef urunlerden biri degil)
         */
        TeshisYanit: {
            /**
             * Etiket
             * @description Model etiketi (ASCII, snake_case).
             */
            etiket: string;
            /**
             * Etiket Tr
             * @description Turkce ad, kullanicida gosterilir.
             */
            etiket_tr: string;
            /** Guven */
            guven: number;
            /**
             * Margin
             * @description Top1 - Top2 guven farki.
             */
            margin: number;
            /**
             * Seviye
             * @description kesin | olasi | belirsiz | tanimsiz
             */
            seviye: string;
            /** Belirsiz */
            belirsiz: boolean;
            /**
             * Sebep
             * @description hedef_disi | cekismeli | orta_guven | guven_dusuk
             */
            sebep?: string | null;
            /**
             * Urun
             * @description Tahmin edilen urun grubu (ornek 'domates').
             */
            urun?: string | null;
            /** Urun Tr */
            urun_tr: string | null;
            /** Urun Guven */
            urun_guven: number;
            /** Topk */
            topk: components["schemas"]["TopKMadde"][];
            /** @description treatments.yaml kaydi. Saglikli/tanimsiz icin null. */
            tedavi?: components["schemas"]["TedaviKaydi"] | null;
            /**
             * Uyari
             * @description Seviyeye gore kullaniciya mesaj.
             */
            uyari?: string | null;
            /**
             * Isi
             * @description Sinif etkinlik haritasi (CAM), 7x7, 0-1 arasi normalize. Top-1 sinifin logitinin mekansal ayrisimi: kareler toplandiginda modelin o sinifa verdigi puani yeniden kurar. Model dosyasi yamalanmamissa null.
             */
            isi?: number[][] | null;
            /** @description Isi haritasinin oturdugu kare. */
            kirpma?: components["schemas"]["Kirpma"] | null;
            /** @description Sezon günlüğü gönderildiyse ve aynı hastalık daha önce de teşhis edildiyse dolar. Fotoğraftan çıkmaz; geçmiş kayıttan çıkar. */
            tekrar?: components["schemas"]["TekrarKaydi"] | null;
        };
        /** TkgmParsel */
        TkgmParsel: {
            /** Bolge */
            bolge: string;
            /** Etiket */
            etiket: string;
            /** Il */
            il: string;
            /** Ilce */
            ilce: string;
            /** Mahalle */
            mahalle: string;
            /** Ada */
            ada: string;
            /** Parsel */
            parsel: string;
            /** Mevkii */
            mevkii?: string | null;
            /** Nitelik */
            nitelik?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alan M2 */
            alan_m2: number;
            /** Dekar */
            dekar: number;
        };
        /** TopKMadde */
        TopKMadde: {
            /**
             * Etiket
             * @description Model etiketi, ornek 'domates_erken_yaniklik'.
             */
            etiket: string;
            /**
             * Etiket Tr
             * @description Okunabilir Turkce ad.
             */
            etiket_tr: string;
            /** Guven */
            guven: number;
        };
        /** ToprakYanit */
        ToprakYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Durum
             * @description "ok" ise sonuç kesindir. Başka bir değerse SoilGrids yanıt vermedi, toprak "yok" değil BİLİNMİYOR demektir.
             */
            durum: string;
            /** Kesin */
            kesin: boolean;
            toprak?: components["schemas"]["SoilData"] | null;
            /**
             * Kaynak Mesafe Km
             * @description 0 ise değer tam bu noktanın. Büyükse SoilGrids bu noktada boştu ve değer bu kadar uzaktaki komşu noktadan alındı.
             */
            kaynak_mesafe_km?: number | null;
            /** Doku Sinifi */
            doku_sinifi?: string | null;
            /** Sure S */
            sure_s: number;
        };
        /** UrunRiski */
        UrunRiski: {
            /** Urun */
            urun: string;
            /** Urun Tr */
            urun_tr: string;
            /** Riskler */
            riskler: components["schemas"]["RiskMaddesi"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ZararliDurumu */
        ZararliDurumu: {
            /** Zararli */
            zararli: string;
            /** Toplam Gdd */
            toplam_gdd: number;
            /** Nesil */
            nesil: number;
            /** Evre */
            evre: string;
            /** Sonraki Evre Ad */
            sonraki_evre_ad?: string | null;
            /** Sonraki Evre Gdd */
            sonraki_evre_gdd?: number | null;
            /** Aciklama */
            aciklama: string;
        };
        /** ZararliYanit */
        ZararliYanit: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Gun */
            gun: number;
            /**
             * Biofix
             * @description Derece-gün birikiminin başladığı tarih.
             */
            biofix: string;
            /** Durumlar */
            durumlar: components["schemas"]["ZararliDurumu"][];
            /** Uyari */
            uyari: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saglik_saglik_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    konum_konum_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonumYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toprak_toprak_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToprakYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    besin_karnesi_uc_besin_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Bilgi tabanındaki ürün anahtarı. Verilirse ürünün pH aralığı ve verimlilik ihtiyacı toprakla karşılaştırılır. */
                urun?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BesinYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parseller_parseller_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Arama yarıçapı. Geniş yarıçap Overpass'ta 504 aldığı için üst sınır 10 km. */
                yaricap_m?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsellerYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oneri_oneri_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Kaç ürün dönsün */
                adet?: number;
                /** @description Tek bir ürün grubuyla sınırla (tahıl, sebze, meyve ...) */
                grup?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneriKumesi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oneri_gruplar_oneri_gruplar_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                grup_basina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rastgele_rastgele_get: {
        parameters: {
            query?: {
                /** @description Aynı noktayı tekrar üretmek için */
                tohum?: number | null;
                deneme?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonumYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kisayollar_kisayollar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KisayolYanit"][];
                };
            };
        };
    };
    urunler_urunler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    teshis_teshis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_teshis_teshis_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeshisYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kapsam_listesi_kapsam_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KapsamYanit"][];
                };
            };
        };
    };
    sulama_sulama_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Ürün anahtarı. Boş bırakılırsa bölge hedef ürünleri (domates, biber, patates) kullanılır. */
                urun?: string | null;
                /** @description ini=başlangıç, mid=gelişme, end=hasat */
                asama?: string;
                /** @description Parsel alanı. Verilirse L/gün hesaplanır. */
                alan_m2?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SulamaYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gunluk_su_acigi_gunluk_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Kc gerektiği için zorunlu. */
                urun: string;
                /** @description Son sulama tarihi (YYYY-AA-GG). */
                son_sulama: string;
                /** @description ini=başlangıç, mid=gelişme, end=hasat */
                asama?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GunlukYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iklim_risk_iklim_riski_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Ürün anahtarı. Boş bırakılırsa bölge hedef ürünleri (domates, biber, patates) kullanılır. */
                urun?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IklimRiskYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zararli_zararli_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Ürün anahtarı. Boş bırakılırsa bölge hedef ürünleri (domates, biber, patates) kullanılır. */
                urun?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZararliYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    karbon_ayak_izi_karbon_get: {
        parameters: {
            query: {
                /** @description Enlem */
                lat: number;
                /** @description Boylam */
                lon: number;
                /** @description Ürün anahtarı (sulama kapsamında olmalı). */
                urun: string;
                /** @description Parsel alanı (m2). */
                alan_m2: number;
                /** @description Sulama sezonu uzunluğu (gün). */
                sezon_gun?: number;
                /** @description Uygulanan saf azot kg/dekar. Boşsa tablo varsayılanı. */
                azot_kg_da?: number | null;
                /** @description Yakıt litre/dekar. Boşsa varsayılan. */
                dizel_l_da?: number | null;
                sulama_yontemi?: string;
                su_kaynagi?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KarbonYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sor_sor_get: {
        parameters: {
            query: {
                /** @description Örn: 'domatese kaç litre su vermeliyim' */
                soru: string;
                lat?: number | null;
                lon?: number | null;
                alan_m2?: number | null;
                /** @description Sezon günlüğündeki son sulama tarihi (YYYY-AA-GG). Yalnızca sulama sorularında kullanılır. */
                son_sulama?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoruYanit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tkgm_parselleri_parseller_tkgm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TkgmParsel"][];
                };
            };
        };
    };
}
